### ISSUE TITLE
Pas possible d'ajouter dans HACS

### ISSUE THREAD

**Issue by freeasabeer** [alexandreaudrain/ecowatt-card#1]
Si j'essaie d'ajouter le dépôt dans HACS, j'ai le message d'erreur suivant:
<Plugin alexandreaudrain/ecowatt-card> Repository structure for Initial is not compliant

**Comment by alexandreaudrain** [comment]
Bonjour, oui je bosse dessus.
Pas moyen de comprendre ce qui coince...         :/

**Comment by alexandreaudrain** [comment]
J'avais un tag qui trainait dans github.
Ca doit fonctionner correctement maintenant.
Peux-tu confirmer, s'il te plait ?

**Comment by freeasabeer** [comment]
Ça marche !
Merci.
